apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: yaelitrovnik/crypto-be:latest
        imagePullPolicy: Always # Clears warning
        resources: # Clears warning
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        env:
        - name: MYSQL_HOST
          value: "mysqldb"
        - name: MYSQL_PASSWORD
          value: "123456"
        - name: MYSQL_USER
          value: "root"
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001